"""
Standalone test script for the broadcast compositor.
Run directly to produce output_news.mp4 using the sample DATA below.

NOTE: DATA is hardcoded for quick visual testing only.
In the real pipeline, all fields are generated by generate_segment_script().
Full rendering logic lives in process/broadcast/.
"""
import PIL.Image as _PILImage
if not hasattr(_PILImage, "ANTIALIAS"):
    _PILImage.ANTIALIAS = _PILImage.LANCZOS

from pathlib import Path
from process.broadcast import render

DURATION = 30.0
OUT      = Path("output_news.mp4")

DATA = {
    "headline_white": "MANCHESTER UNITED",
    "headline_red":   "SIGN STRIKER IN £80M DEAL",
    "source":         "Source: Sky Sports Football",
    "deal_points": [
        {
            "text":      "Manchester United have completed the signing of a new striker in a blockbuster £80m deal.",
            "highlight": None,
            "icon_fill": (160, 0, 0),
        },
        {
            "text":      "The player has signed a five-year contract valid until June 2029 with an option to extend.",
            "highlight": "June 2029",
            "icon_fill": (30, 30, 30),
        },
        {
            "text":      "Official announcement from the club is expected within the next 24 to 48 hours.",
            "highlight": None,
            "icon_fill": (30, 30, 30),
        },
    ],
    "ticker": (
        "Manchester United Sign Striker in £80m Deal"
        "  •  Sky Sports Football"
        "  •  Football Credo Hub"
        "  •  Football News. Every Second."
    ),
    "player_image":   None,
    "left_video":     "storage/Videos/Cache/pexels/pexels_198af9b3fd.mp4",
    "breaking_label": "BREAKING NEWS",
    "deal_label":     "Deal Confirmed",
    "voiceover":      "storage/Voiceovers/test_001_main_english.mp3",
}

if __name__ == "__main__":
    print("Rendering output_news.mp4 …")
    render(DATA, OUT, DURATION)
    print(f"Done  ->  {OUT.resolve()}")
