"""
Shared data types for the entire pipeline.
All modules import NewsItem, Script, etc. from here — never from each other.
"""
import hashlib
from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal

# ── Type aliases ──────────────────────────────────────────────────────────────

SourceType  = Literal["rss", "google_alerts"]
ContentType = Literal["breaking_news", "transfer_rumour", "club_update", "tactical"]


# ── Data classes ──────────────────────────────────────────────────────────────

@dataclass
class NewsItem:
    """One news article from any source."""
    id:          str           # SHA-256 hash of headline (deduplication key)
    headline:    str
    body:        str
    url:         str
    source:      str           # e.g. "Sky Sports Football"
    source_type: SourceType
    timestamp:   datetime
    raw:         dict = field(default_factory=dict, repr=False)

    @staticmethod
    def make_id(headline: str) -> str:
        return hashlib.sha256(headline.strip().lower().encode()).hexdigest()[:16]


@dataclass
class Script:
    """Generated script for a NewsItem."""
    news_id:                    str
    script_type:                ContentType
    format:                     str   # "main" | "short"
    text:                       str
    word_count:                 int
    estimated_duration_seconds: int


@dataclass
class VideoMetadata:
    """YouTube upload metadata, auto-generated by publish/youtube.py."""
    title:          str
    description:    str
    tags:           list[str]
    category_id:    str       = "17"       # 17 = Sports
    privacy_status: str       = "private"
    publish_at:     str | None = None      # ISO 8601 — triggers scheduled publish


@dataclass
class PipelineResult:
    """Result returned by pipeline/orchestrator.py after processing one item."""
    news_id:          str
    success:          bool
    youtube_video_id: str | None = None
    error:            str | None = None
