"""
Social media poster — Step 10.

Posts a video clip to:
  TikTok, Instagram Reels, X (Twitter), YouTube Shorts
via the Buffer API.

Captions are auto-generated by Groq.
"""
import logging
from pathlib import Path

import requests
from openai import OpenAI

from config import settings
from core.types import NewsItem, Script

logger = logging.getLogger(__name__)

_BUFFER_BASE = "https://api.bufferapp.com/1"
_groq = OpenAI(api_key=settings.GROQ_API_KEY, base_url="https://api.groq.com/openai/v1")

_CAPTION_PROMPT = """Write a punchy social media caption for a 15-second football news clip.

Script: {script_text}
Brand: {brand_name}

Rules:
- Max 150 characters for the caption text
- Include 5 highly relevant football hashtags at the end
- Tone: energetic, urgent, social-native
- End with: "Follow {brand_name}"

Return ONLY the caption text with hashtags. No labels."""


def _generate_caption(script: Script) -> str:
    try:
        resp = _groq.chat.completions.create(
            model=settings.GROQ_MODEL,
            messages=[{"role": "user", "content": _CAPTION_PROMPT.format(
                script_text=script.text,
                brand_name=settings.BRAND_NAME,
            )}],
            max_tokens=100,
            temperature=0.7,
        )
        return resp.choices[0].message.content.strip()
    except Exception as e:
        logger.warning("Caption generation failed: %s", e)
        return f"Football news just in! Follow {settings.BRAND_NAME} for updates. #Football #FootballNews #Transfers"


def _post_to_buffer(profile_id: str, caption: str, video_path: Path, platform: str) -> None:
    with open(video_path, "rb") as f:
        upload = requests.post(
            f"{_BUFFER_BASE}/media/upload.json",
            headers={"Authorization": f"Bearer {settings.BUFFER_ACCESS_TOKEN}"},
            files={"file": (video_path.name, f, "video/mp4")},
            timeout=120,
        )
    upload.raise_for_status()
    media_id = upload.json().get("id")

    post = requests.post(
        f"{_BUFFER_BASE}/updates/create.json",
        headers={"Authorization": f"Bearer {settings.BUFFER_ACCESS_TOKEN}"},
        data={
            "profile_ids[]":    profile_id,
            "text":             caption,
            "media[video_id]":  media_id,
            "now":              "true",
        },
        timeout=30,
    )
    post.raise_for_status()
    logger.info("Posted to %s via Buffer", platform)


def post_short_to_socials(short_video_path: Path, item: NewsItem, script: Script) -> None:
    """Post the 15-second vertical clip to all configured social platforms."""
    if not short_video_path.exists():
        logger.warning("Short video not found, skipping social post: %s", short_video_path)
        return

    caption   = _generate_caption(script)
    platforms = [
        (settings.BUFFER_PROFILE_ID_TIKTOK,    "TikTok"),
        (settings.BUFFER_PROFILE_ID_INSTAGRAM,  "Instagram Reels"),
        (settings.BUFFER_PROFILE_ID_TWITTER,    "X (Twitter)"),
        (settings.BUFFER_PROFILE_ID_YOUTUBE,    "YouTube Shorts"),
    ]

    for profile_id, name in platforms:
        if not profile_id:
            logger.info("Skipping %s — no profile ID configured", name)
            continue
        try:
            _post_to_buffer(profile_id, caption, short_video_path, name)
        except Exception as e:
            logger.error("Failed to post to %s: %s", name, e)
